group "CGConceptTest/LearnOpenGL"
    include "CGConceptTest/src/Learn_OpenGL/glfwConf"
    include "CGConceptTest/src/Learn_OpenGL/gladConf"
    include "CGConceptTest/src/Learn_OpenGL/HelloTriangle"
    include "CGConceptTest/src/Learn_OpenGL/Shaders"
    include "CGConceptTest/src/Learn_OpenGL/Texture"
group ""